# -*- coding: utf-8 -*-
"""Assignment10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MXkPNXse3VGY-QLzgk1-HQzkhfRERUc
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

header=["id","RI","Na","Mg","AI","Si","K","Ca","Ba","Fe","Type_of_Glass"]
df = pd.read_csv('trainKNN.txt',names=header)
X_train=df[['RI','Na','Mg','AI','Si','K','Ca','Ba','Fe']]
y_train=df[['Type_of_Glass']]

df2=pd.read_csv('testKNN.txt',names=header)
df2.head()
X_test=df2[['RI','Na','Mg','AI','Si','K','Ca','Ba','Fe']]
y_test=df2[['Type_of_Glass']]

model1=KNeighborsClassifier(metric='euclidean',n_neighbors=5)
model1.fit(X_train,y_train)
y_pred_m1  =  model1.predict(X_test)

model2=KNeighborsClassifier(metric='manhattan',n_neighbors=5)
model2.fit(X_train,y_train)
y_pred_m2  =  model2.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("KNN with 'Euclidean' Distance Metric")
print("Test Accuracy : ", model1.score(X_test,y_test)) 
print(classification_report(y_test,y_pred_m1))
print("KNN with 'Manhattan' Distance Metric")
print("Test Accuracy : ", model2.score(X_test,y_test)) 
print(classification_report(y_test,y_pred_m2))