# -*- coding: utf-8 -*-
"""Decision_Trees_Assignment15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YnRBPfTkN8QmP-d_TVgirdl9Oc6qWtkO
"""

#Social_Network_Ads.csv

"""**Importing the libraries**"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

"""**Importing the dataset**"""

data=pd.read_csv('Social_Network_Ads.csv')
data=data.drop('User ID',axis=1)
le=LabelEncoder()
data['Gender']=le.fit_transform(data['Gender'])
x=data[['Gender','Age','EstimatedSalary']]
y=data[['Purchased']]

"""**Splitting the dataset into the Training set and Test set**"""

X_Train,X_Test,y_Train,y_Test=train_test_split(x,y,test_size=0.25,random_state=1)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_Train=sc.fit_transform(X_Train)
X_Test=sc.transform(X_Test)

"""**Fitting Decision Tree Classification to the Training set**"""

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_Train,y_Train)

"""**Predicting the Test set results**"""

y_pred = model.predict(X_Test)

"""**Making the Confusion Matrix**"""

from sklearn.metrics import confusion_matrix,plot_roc_curve,accuracy_score,f1_score
print(confusion_matrix(y_Test,y_pred))
print(accuracy_score(y_Test,y_pred))
print(f1_score(y_Test,y_pred))

"""**Visualising the Training set results**"""

plot_roc_curve(model,X_Train,y_Train)

"""**Visualising the Test set results**"""

plot_roc_curve(model,X_Test,y_Test)







