# -*- coding: utf-8 -*-
"""Logistic_Regression_Assignment12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1045sup4w5qqn5ewaLSq9LKl15LEXGsP1
"""

# Social_Network_Ads.csv

"""This dataset contains information of users in a social network. Those informations are the user id the gender the age and the estimated salary. A car company has just launched their brand new luxury SUV. And we're trying to see which of these users of the social network are going to buy this brand new SUV And the last column here tells If yes or no the user bought this SUV we are going to build a model that is going to predict if a user is going to buy or not the SUV based on two variables which are going to be the age and the estimated salary. So our matrix of feature is only going to be these two columns. We want to find some correlations between the age and the estimated salary of a user and his decision to purchase yes or no the SUV.

**Step 1 | Data Pre-Processing**

**Importing the Libraries**
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split



"""**Importing the dataset**"""

data=pd.read_csv('Social_Network_Ads.csv')
data.info()

data=data.drop('User ID',axis=1)
label_encode=LabelEncoder()
data['Gender']=label_encode.fit_transform(data['Gender'])

"""**Splitting the dataset into the Training set and Test set**"""

x=data[['Gender','Age','EstimatedSalary']]
y=data[['Purchased']]
X_Train,X_Test,y_Train,y_Test=train_test_split(x,y,test_size=0.25,random_state=2)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_Train=sc.fit_transform(X_Train)
X_Test=sc.transform(X_Test)

"""**Step 2 | Logistic Regression Model**

The library for this job which is going to be the linear model library and it is called linear because the logistic regression is a linear classifier which means that here since we're in two dimensions, our two categories of users are going to be separated by a straight line. Then import the logistic regression class. Next we will create a new object from this class which is going to be our classifier that we are going to fit on our training set.

**Fitting Logistic Regression to the Training set**
"""

from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()
lr_model.fit(X_Train, y_Train)

"""**Step 3 | Predection**"""

lr_model.predict(X_Test)

"""**Step 4 | Evaluating The Predection**

We predicted the test results and now we will evaluate if our logistic regression model learned and understood correctly. So this confusion matrix is going to contain the correct predictions that our model made on the set as well as the incorrect predictions.

**Making the Confusion Matrix**
"""

y_Test_predictions = lr_model.predict(X_Test)
y_Test_predictions

from sklearn.metrics import confusion_matrix,plot_roc_curve,accuracy_score
cnf_matrix = confusion_matrix(y_Test, lr_model.predict(X_Test))
print(cnf_matrix)
print(accuracy_score(y_Test, lr_model.predict(X_Test)))

"""**Visualization**"""

plot_roc_curve(lr_model, X_Test, y_Test)



